export const LOADING_STAFFS="LOADING_STAFFS";
export const GET_ALL_STAFFS_SUCCESS = "GET_ALL_STAFFS_SUCCESS";
export const GET_ALL_STAFFS_FAIL = "GET_ALL_STAFFS_FAIL";


export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS";
export const ADD_STAFF_FAIL = "ADD_STAFF_FAIL";


export const DELETE_STAFF_SUCCESS = "DELETE_STAFF_SUCCESS";
export const DELETE_STAFF_FAIL = "DELETE_STAFF_FAIL";

export const GET_ONE_STAFF_SUCCESS = "GET_ONE_STAFF_SUCCESS";
export const GET_ONE_STAFF_FAIL = "GET_ONE_STAFF_FAIL";

export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS";
export const UPDATE_STAFF_FAIL = "UPDATE_STAFF_FAIL";

